name: CI/CD for React TypeScript Portfolio

# Jalankan saat ada perubahan di branch `main`
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Sesuaikan dengan versi yang Anda gunakan

      # Langkah 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Langkah 4: Run tests
      - name: Run tests
        run: npm test -- --ci --coverage --watchAll=false
        env:
          CI: true

      # Langkah 5: Build React App (jika testing berhasil)
      - name: Build React App
        run: npm run build

      # Langkah 6: Deploy to GitHub Pages (opsional jika Anda menggunakan GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
